# Generated by Django 5.0.6 on 2024-10-24 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='todos',
        ),
        migrations.AddField(
            model_name='todo',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project1.project'),
        ),
    ]
