# Generated by Django 5.0.6 on 2024-10-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0003_alter_todo_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
