# Generated by Django 5.0.6 on 2024-10-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0005_alter_todo_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='unique_id',
            field=models.CharField(max_length=100),
        ),
    ]
